IMPALA-11758: Fixed error detection for usage of reserved words.
Fixed the control flow of checking whether the parsing failed on the
usage of a reserved word where an identifier was expected. Added a hint
to the error message on how to fix the query.

Query: create database iceberg
ERROR: ParseException: Syntax error in line 1:
create database iceberg
                ^
Encountered: ICEBERG
Expected: DEFAULT, EXTENDED, FORMATTED, IF, IDENTIFIER

Hint: reserved words have to be escaped when used as an identifier, e.g. `iceberg`

CAUSED BY: Exception: Syntax error

Testing:
 - Added new tests to test_reserved_words_version.py
 - Adjusted ParserTests
 - Built docs

Change-Id: I9605d80a25ff878d12f6ca2ebb99ac26298d8efa
Reviewed-on: http://gerrit.cloudera.org:8080/19290
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>