IMPALA-4384: NPE when cols list has trailing comma
The changes to introduce new PRIMARY KEY syntax allowed for
a table definition to have a list of cols, optionally
followed by a PRIMARY KEY clause. However, this rule
was broken and would allow for the list of columns followed
by a trailing comma.

[localhost:21000] > create table foo (id int, x int,);
Query: create table foo (id int, x int,)
ERROR: AnalysisException: null
CAUSED BY: NullPointerException: null

Change-Id: Ibc394dd7e687b501ae7887a51bed2f441d562760
Reviewed-on: http://gerrit.cloudera.org:8080/4869
Reviewed-by: Matthew Jacobs <mj@cloudera.com>
Tested-by: Internal Jenkins