IMPALA-7513: Fix Sentry compilation error in 2.x
An update to Sentry 1.5.1-cdh5.16.0-SNAPSHOT broke the build. This patch
fixes it by uploading the new CDH components, which includes Sentry server
to make sure the Sentry client and server dependencies are coherent.

Testing:
- Ran FE tests

Change-Id: I99c1aba398ea798a80fbbf76b4c5f8ad289be2ad
Reviewed-on: http://gerrit.cloudera.org:8080/11362
Reviewed-by: Fredy Wijaya <fwijaya@cloudera.com>
Reviewed-by: Quanlong Huang <huangquanlong@gmail.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>