single_node_perf_run.py: clean up newly-added testdata
In single_node_perf_run.py, restore_workloads() can make the tree
"dirty", and when a tree is dirty, git won't let you switch branches
in a way that clobbers the dirty file contents:

    $ cd $(mktemp -d)
    $ git init .
    Initialized empty Git repository in /tmp/tmp.H0NxzTXLUj/.git/
    $ touch foo && git add foo && git commit -a -m "foo"
    [master (root-commit) 3776149] foo
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 foo
    $ git checkout -b ok_foo && echo "ok" >> foo && git commit -a -m "foo is ok"
    Switched to a new branch 'ok_foo'
    [ok_foo 9fd5bde] foo is ok
     1 file changed, 1 insertion(+)
    $ git checkout master && echo "not ok" >> foo
    Switched to branch 'master'
    $ git checkout ok_foo
    error: Your local changes to the following files would be overwritten by checkout:
            foo
    Please, commit your changes or stash them before you can switch branches.
    Aborting

Discovered when testing single_node_perf_run with
https://gerrit.cloudera.org/#/c/7153/; after this commit, that patch
works with single_node_perf_run.py

Change-Id: Id0220f3cd7a26d2627e40cd432c23815a6d65ea4
Reviewed-on: http://gerrit.cloudera.org:8080/7291
Reviewed-by: Jim Apple <jbapple-impala@apache.org>
Tested-by: Impala Public Jenkins