IMPALA-14217: Fixes Incompatibility with OpenSSL 1.0
A new function `ValidatePemBundle` was introduced in openssl-utl.cc
under IMPALA-13237. This function used the X509_get0_notBefore and
X509_get0_notAfter functions which were introduced in OpenSSL 1.1.0.

Fixes compilation errors with OpenSSL 1.0.x by reverting to the older
X509_get_notBefore and X509_get_notAfter functions. These functions
were deprecated in OpenSSL 1.1.1 but are drop-in replacements for
X509_get0_notBefore and X509_get0_notAfter differing only in the
function return being mutable vs const.

Fixes flaky tests failing because different versions of OpenSSL set
different error codes in the BIO_new_mem_buf() function.

Tested locally by compiling and running openssl-util-test ctests.
Also built and ran tests using Jenkins on RHEL 8.6 and CentOS 7.4.

Change-Id: If58a12f14a5509d62b7cfe291372b53b440da511
Reviewed-on: http://gerrit.cloudera.org:8080/23161
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>