IMPALA-9627 (followup): Switch push_to_asf.py to python 3
push_to_asf.py asks the user for input. This recently
switched from raw_input() to input(), because Python 3
doesn't have a raw_input() function.

Python 2's input() function has weird semantics. At the
"[Y/n]:" prompt, typing y (no quotes) produces this error:
NameError: name 'y' is not defined

Instead, it wants 'y' (with quotes). This is because Python 2's
input() function wants a python expression. This switches the
script to use python3, which has the old behavior from
raw_input().

Testing:
 - Ran script with Python 3, hand tested the confirm_prompt function

Change-Id: Ida49993bfea71ade9d335ac1ceb53788d0a57f69
Reviewed-on: http://gerrit.cloudera.org:8080/19817
Reviewed-by: Michael Smith <michael.smith@cloudera.com>
Tested-by: Joe McDonnell <joemcdonnell@cloudera.com>