IMPALA-7971 (follow-up). Fix compilation error
15a33d1ba was committed at about the same time as 5ced9160bd6, which
renamed one of the methods of the FileDescriptor class, causing a
compilation error. This follow-up mixes the semantic conflict.

Tested tests/custom_cluster/test_event_processing.py manually.

Change-Id: I8071b421f0dcbae2d303bd9f1e1f6f64657c49c0
Reviewed-on: http://gerrit.cloudera.org:8080/13184
Reviewed-by: Todd Lipcon <todd@apache.org>
Tested-by: Todd Lipcon <todd@apache.org>