IMPALA-11938: Raised error if NUM_NODES is set to invalid value.
If NUM_NODES is set to a value other than 0 or 1 below error is raised
ERROR: Invalid value for query option NUM_NODES: <value> is not in range [0, 1]

Change-Id: Ib283ae350875a7ac217490c216a26281f1bb4812
Reviewed-on: http://gerrit.cloudera.org:8080/21147
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>