IMPALA-14563: Throw AnalysisException when aggregating complex type
Before this change, when the user tries to aggregate by a complex type,
we threw an IllegalStateException.

  SELECT complex_col, count(*) FROM table_example GROUP BY complex_col;

Error:

  java.lang.IllegalStateException: null

This does not provide appropriate context about the query's problem.

Instead of throwing an IllegalStateException, we now throw the
appropriate AnalysisException, which highlights the issue with the query.

  AnalysisException: GROUP BY expression cannot be used on complex types
                     without specifying a field

This helps the user rewrite the query correctly by making them aware that
specifying a field would fix the query.

  SELECT complex_col.val1, count(*) FROM table_example GROUP BY complex_col.val1;

Testing:
  Added tests to TestsGroupBy() method in AnalyzeStmtsTest.java

Change-Id: Ie431873efe7100e8150e93be2aa016381d687268
Reviewed-on: http://gerrit.cloudera.org:8080/23855
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Reviewed-by: Noemi Pap-Takacs <npaptakacs@cloudera.com>