Revert "IMPALA-14454: Exclude log4j 2 dependencies"
This reverts commit 52b87fcefd26dbf6fea751378bd23e0fb7e0d18a.

The original commit caused an issue when Impala is deployed together
with Apache Atlas. Coordinator failed to start with error message:

java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Layout

Solved minor conflict in impala-config.sh due to IMPALA-14478 applied
after IMPALA-14454.

Change-Id: I77127db8d833c675c18c30eb3d6542ca906cd2a9
Reviewed-on: http://gerrit.cloudera.org:8080/23788
Reviewed-by: Michael Smith <michael.smith@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>