IMPALA-7490: fix uninitialized variables in load-data.py
Fixes use of an uninitialized variable in bin/load-data.py

I found the following error message in a failed build, which is quite
misleading:

Traceback (most recent call last):
  File "bin/load-data.py", line 495, in <module>
    if __name__ == "__main__": main()
  File "bin/load-data.py", line 459, in main
    impala_exec_query_files_parallel(thread_pool, impala_create_files)
  File "bin/load-data.py", line 297, in impala_exec_query_files_parallel
    exec_query_files_parallel(thread_pool, query_files, 'impala')
  File "bin/load-data.py", line 291, in exec_query_files_parallel
    for result in thread_pool.imap_unordered(execution_function, query_files):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
UnboundLocalError: local variable 'query' referenced before assignment

The error is trown from the 'execution_function' which is
'exec_impala_query_from_file' in my case. Should not use 'query' if it's
undefined.

Change-Id: If0dd56a9b78a60b3a9f04d9f61e93b4b5d066b76
Reviewed-on: http://gerrit.cloudera.org:8080/11330
Reviewed-by: Quanlong Huang <huangquanlong@gmail.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>