Enabling C++14 for non-crosscompiled code.
This patch does nothing more than passing the command-line flag to GCC
to enable compilation according to the C++14 standard. No other
functional changes to the code are applied.

It's important to mention that C++14 is only valid now for
non-crosscompiled code and code that is not included during the
cross-compilation. The reason is that LLVM 3.3 is too old for C++11/14
and the result are compilation errors. Only an upgrade to a higher LLVM
version will fix that.

Change-Id: I2bcd4a1aaeb3d47c27b94a2ffd7ee01a33eea85c
Reviewed-on: http://gerrit.cloudera.org:8080/1632
Tested-by: Internal Jenkins
Reviewed-by: Dan Hecht <dhecht@cloudera.com>