IMPALA-12386: Fix clone constructor in CastExpr
This commit addresses an issue in the CastExpr class where the clone
constructor was not properly preserving compatibility settings. The
clone constructor assigned the default compatibility regardless of the
source expression, causing substitution errors for partitioned tables.

Example:
  'insert into unsafe_insert_partitioned(int_col, string_col)
   values("1", null), (null, "1")'
Throws:
  ERROR: IllegalStateException: Failed analysis after expr substitution.
  CAUSED BY: IllegalStateException: cast STRING to INT

Tests:
  - new test case added to insert-unsafe.test

Change-Id: Iff64ce02539651fcb3a90db678f74467f582648f
Reviewed-on: http://gerrit.cloudera.org:8080/20385
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>