IMPALA-12696: Update HS2 definitions (TCLIService.thrift)
Update to "fresh" (didn't change since 2022) TCLIService.thrift
from Hive repo.
Mainly a copy of Hive version, but some changes were needed:
- change python namespace to impala_thrift_gen.TCLIService
- reorder a few structs to avoid compilation errors in c++
- readd GetLog()

Implements one of the new functions (GetQueryId) and returns
"not implemented" error for others.

Realized last minute that there is a very similar prototype
review:
https://gerrit.cloudera.org/#/c/20495/
My change does almost the same, but updates to a bit newer version
and does not change server behavior, e.g. doesn't bump
MAX_SUPPORTED_HS2_VERSION. The main motivation is providing the
generated python artifacts for impyla which is also used with Hive.
Using the new possibilites in the protocol could be done in follow up
patches.

Generated-by: Cloude Sonnet 4.6

Change-Id: I52027d65c726a7f3abd4557a45c5ddd832fbb6bc
Reviewed-on: http://gerrit.cloudera.org:8080/24376
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Reviewed-by: Csaba Ringhofer <csringhofer@cloudera.com>
Tested-by: Csaba Ringhofer <csringhofer@cloudera.com>