IMPALA-13786: Skip rewriting expr of Hive auto-generated label
IMPALA-10836 introduced the SimplifyCastExprRule optimization to
simplify CAST expressions. However, applying this rewrite rule over
expression referred by Hive auto-generated label has caused
AnalysisException like following:

AnalysisException: Could not resolve column/field reference:
'failing_view._c0'

It is most likely that, before IMPALA-10836, expression referred by Hive
auto-generated label never effectively being rewritten. Thus, the
ExprSubstitutionMap across multiple InlineViewRef was intact.

This patch attempt to fix the issue by making any expression in
SelectList that mapped to Hive auto-generated label ineligible for any
kind of expression rewrite.

Also addressed some flake8 errors in test_views_compatibility.py.

Testing:
- Add test case in views-compatibility.test.
- Break test_view_compatibility_hive into 3 separate tests.
- Refactor test_views_compatibility.py to run both EXPLAIN and SELECT
  query over the test view.
- Pass test_views_compatibility.py in exhaustive exploration.
- Pass core tests.

Change-Id: I4b8bbd0afd6da0532bf2ef460989d4f01337d198
Reviewed-on: http://gerrit.cloudera.org:8080/22546
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>